python trainer.py \
  --data-dir ../data \
  --lr 0.01 \
  --batch-size 160 \
  --world_size 5 \
  --skew 1 \
  --gamma 0.1 \
  --normtype evonorm \
  --optimizer engc \
  --epoch 50 \
  --arch cganet \
  --momentum 0.9 \
  --alpha 1.0 \
  --graph ring \
  --neighbors 2 \
  --nesterov \
  --use-edl \
  --engc-tau-u 0.5 \
  --engc-wa 0.5 \
  --noise-rate 0.3 \
  --noise-agents "0,1" \