# Each experiment produces under outputs/<run_id>/:
#   training_log.txt               — full console log (config, non-IID, results)
#   train_accuracy_vs_epoch.png    — generated by trainer.py
#   val_accuracy_vs_epoch.png      — generated by trainer.py
#   excel_data/                    — serialised per-rank metrics

set -u

OUTDIR="outputs"
PORT=25500

# Common hyperparameters (shared by every run)
COMMON=(
    --lr 0.01
    --batch-size 160
    --skew 1.0
    --gamma 0.1
    --normtype evonorm
    --epochs 100
    --arch cganet
    --momentum 0.9
    --alpha 1.0
    --nesterov
    --weight_decay 1e-4
    --steplr
)

# Dataset args
HAM=(--data-dir ../data/ham10000   --dataset ham10000   --classes 7)
ISIC=(--data-dir ../data/fedisic2019 --dataset fedisic2019 --classes 8)

# Topology args
RING=(--graph ring --neighbors 2)
FULL5=(--graph full --neighbors 4)
FULL10=(--graph full --neighbors 9)

# Optimizer args
OPT_NGC=(--optimizer ngc)
OPT_ENGC=(--optimizer engc --use-edl --edl-lambda 1.0)
OPT_CGA=(--optimizer cga)
OPT_ALPHA=(--optimizer adaptive_ngc)
OPT_TOPK=(--optimizer topkngc)
OPT_MURMURA=(--optimizer murmura)

# run_exp <optimizer_name> <world_size> <graph_name> [extra trainer args...] ─

run_exp() {
    local opt="$1" nodes="$2" graph="$3"
    shift 3

    local run_id="${opt}_cganet_nodes_${nodes}_evonorm_lr_0.01_gamma_0.1_alpha_1.0_skew_1.0_${graph}"
    local run_dir="${OUTDIR}/${run_id}"

    mkdir -p "${run_dir}/excel_data"

    printf '\n'
    printf '======================================================================\n'
    printf '  STARTING : %s\n' "$run_id"
    printf '  Time     : %s\n' "$(date)"
    printf '======================================================================\n\n'

    python trainer.py "${COMMON[@]}" "$@" --world_size "$nodes" --port "$PORT" \
        2>&1 | tee "${run_dir}/training_log.txt"
    local exit_code=${PIPESTATUS[0]}

    PORT=$((PORT + 1))

    if [ "$exit_code" -ne 0 ]; then
        printf '\n  [FAILED] %s (exit code %d)\n' "$run_id" "$exit_code"
    else
        printf '\n  [OK]     %s | %s\n' "$run_id" "$(date)"
    fi
}


# ==============================================================================
#  FED-ISIC-2019  —  10 nodes - full
# ==============================================================================

printf '\n\n### FED-ISIC-2019 | 10 nodes | Full ###\n'
run_exp engc         10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_ENGC[@]}"
run_exp ngc          10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_NGC[@]}"
run_exp cga          10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_CGA[@]}"
run_exp adaptive_ngc 10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_ALPHA[@]}"
run_exp topkngc      10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_TOPK[@]}"
run_exp murmura      10 full "${ISIC[@]}" "${FULL10[@]}" "${OPT_MURMURA[@]}"

printf '\n\nAll experiments finished: %s\n' "$(date)"
